language: cpp

sudo: required

dist: trusty

compiler:
  - gcc

env:
  global:
    - INSTALL_DIR=~/mylibs
    - CXXFLAGS="-Werror"

script:
  - mkdir build_tmp && cd build_tmp
  - cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR $TRAVIS_BUILD_DIR
  - make
  - make install
  - make examples

before_script:
  - cat /etc/apt/sources.list
  - cat /etc/apt/sources.list.d/*
  - sudo apt-add-repository multiverse
  - sudo apt-get update -qq
  - sudo dpkg --configure -a
  - sudo apt-get install -f -qq
  - sudo dpkg --get-selections | grep hold || { echo "All packages OK."; }
  - sudo apt-get install -q -y cmake-data cmake
  - sudo apt-get install -qq build-essential
  - gcc --version && g++ --version # 4.8
  - apt-cache search nvidia-*
  - sudo apt-get install -qq nvidia-common
  - sudo apt-get install -qq nvidia-cuda-dev nvidia-cuda-toolkit # 5.5
  - sudo apt-get install -qq libboost-dev # 1.54.0
  - sudo find /usr/ -name libcuda*.so

after_script:
  - ls -halR $INSTALL_DIR

